### PR TITLE
d1f8f9xcsvx3ha.cloudfront.net d3e1078hs60k37.cloudfront.net

### PR DESCRIPTION
**Pull request by p1r473**
Hello,
Why are you blocking Cloudfront?
It breaks many sites that host files on Cloudfront, an Amazon service

Amazon CloudFront is a fast content delivery network (CDN) service that securely delivers data, videos, applications, and APIs to customers globally

Not all Cloudfront is Ads

We should not be blocking it everywhere.

Here is an icon image on a website I was browsing that failed to load due to us blocking Cloudfront:
https://d3e1078hs60k37.cloudfront.net/site_files/images/icons/mv-all-icon.svg

Ex of a broken site:

image
image

### CODE REVIEW

**Comment by liamengland1** [comment]
Many cloudfront domains serve ads and tracking scripts, just report the one false positive and any more you find.

**Comment by dnmTX** [comment]
Absolutely agree with @llacb47  and also, @p1r473 ,the pictures you posted above,how is that not advertisement? They selling you things that most of us don't need or won't ever use.
So the question is,what exactly you're considering as advertisement then?

**Comment by p1r473** [comment]
Ok, so the 2 domains I saw that were not ads but were actual site content were 
d1f8f9xcsvx3ha.cloudfront.net
d3e1078hs60k37.cloudfront.net
If we want to whitelist just these
@dnmTX that is not an ad, that is the price listing on the website that sells the software. I went to the website that specifically sells the product, so I could buy it, so its not an ad. An ad would be on a random website, not the actual site that sells it. https://www.stardock.com/products/groupy/download is the actual page for getting the software.

**Comment by dnmTX** [comment]
The link you posted is opening just fine on my end,i even went ahead with purchasing and it went trough. I even checked the page code and none of the mentioned domains were present anywhere.

**Comment by p1r473** [comment]
@dnmTX the image I posted in the original post is how it looks for me with and without blocked:
Maybe you are not using an adlist that blocks d1f8f9xcsvx3ha.cloudfront.net
image
image

**Comment by p1r473** [comment]
Also, here is an icon image on a website I was browsing that failed to load due to us blocking d3e1078hs60k37.cloudfront.net :
https://d3e1078hs60k37.cloudfront.net/site_files/images/icons/mv-all-icon.svg

**Comment by dnmTX** [comment]
You need to update your lists,The `d1f8f9xcsvx3ha.cloudfront.net` domain is not present in Ultimate.Hosts.... after the latest filtering. Neither `d1f8f9xcsvx3ha.cloudfront.net` for a fact.

**Comment by p1r473** [comment]
Thanks, d3e1078hs60k37.cloudfront.net is still on the list though. Ill change the original post.
https://github.com/smed79/blacklist/blob/master/hosts/cloudfront.txt#L512

**Pull request closed without merging**
